SummarizerRole = '''
**Prompt:**

"Provide a concise summary of the paragraphs. Focus on the key points, major developments, and any significant impacts or outcomes. Exclude minor details and provide the summary in a clear and easy-to-understand format."

**Example Usage:**
A. Example 1 (multiple paragraph) 
Input: 
1. <source>
Artificial Intelligence (AI) has rapidly evolved over the past few decades, transforming industries and daily life. From virtual assistants like Siri and Alexa to advanced machine learning models in healthcare and finance, AI's applications are vast and varied. However, alongside its benefits, AI also raises ethical concerns, such as data privacy, job displacement, and algorithmic bias.
</source>
2. <source> 
Climate change is one of the most pressing global issues today. Rising temperatures, melting glaciers, and extreme weather events are clear indicators of a warming planet. Governments and organizations worldwide are working to reduce carbon emissions and promote sustainable practices. Despite these efforts, the challenge remains significant, requiring collective action and innovation.
</source>

3. <source>
In the world of literature, classic novels often serve as mirrors to society, reflecting the values, struggles, and dynamics of their time. Authors like Jane Austen and Charles Dickens provided insightful commentaries on social structures and human nature through their works. These classics remain relevant today, offering timeless lessons and profound observations on human behavior.
</source>


Result:

Summary 1:
AI has advanced significantly, impacting various sectors like healthcare and finance. While offering numerous benefits, it also brings ethical challenges, including data privacy and job displacement.

Summary 2:
Climate change is a critical global issue, evidenced by rising temperatures and extreme weather. Efforts to reduce carbon emissions are ongoing, but substantial challenges persist, necessitating collective action.

Summary 3:
Classic novels by authors like Austen and Dickens reflect societal values and struggles of their era, providing timeless insights into human nature.

B. Example 2 (summary from wikipedia)

Input:
Page: Elon Musk
Summary: Elon Reeve Musk (; born June 28, 1971) is a businessman known for his key roles in the space company SpaceX and the automotive company Tesla, Inc. He is also known for his ownership of X Corp. (the company that operates the social media platform X, formerly Twitter), and his role in the founding of the Boring Company, xAI, Neuralink, and OpenAI. Musk is the wealthiest individual in the world; as of January 2025, Forbes estimates his net worth to be US$421 billion.
A member of the wealthy South African Musk family, Musk was born in Pretoria and briefly attended the University of Pretoria. At the age of 18 he immigrated to Canada, acquiring its citizenship through his Canadian-born mother, Maye. Two years later, he matriculated at Queen's University in Canada. Musk later transferred to the University of Pennsylvania and received bachelor's degrees in economics and physics. He moved to California in 1995 to attend Stanford University but never enrolled in classes, and with his brother Kimbal co-founded the online city guide software company Zip2. The startup was acquired by Compaq for $307 million in 1999. That same year, Musk co-founded X.com, a direct bank. X.com merged with Confinity in 2000 to form PayPal. In 2002, Musk acquired United States citizenship, and that October eBay acquired PayPal for $1.5 billion. Using $100 million of the money he made from the sale of PayPal, Musk founded SpaceX, a spaceflight services company, in 2002. 
In 2004, Musk was an early investor in electric-vehicle manufacturer Tesla Motors, Inc. (later Tesla, Inc.), providing most of the initial financing and assuming the position of the company's chairman. He later became the product architect and, in 2008, the CEO. In 2006, Musk helped create SolarCity, a solar energy company that was acquired by Tesla in 2016 and became Tesla Energy. In 2013, he proposed a hyperloop high-speed vactrain transportation system. In 2015, he co-founded OpenAI, a nonprofit artificial intelligence research company. The following year Musk co-founded Neuralink, a neurotechnology company developing brain–computer interfaces, and the Boring Company, a tunnel construction company. In 2018, the U.S. Securities and Exchange Commission (SEC) sued Musk, alleging he falsely announced that he had secured funding for a private takeover of Tesla. To settle the case, Musk stepped down as the chairman of Tesla and paid a $20 million fine. In 2022, he acquired Twitter for $44 billion, merged the company into his newly-created X Corp. and rebranded the service as X the following year. In 2023, Musk founded xAI, an artificial intelligence company.
Musk's actions and expressed views have made him a polarizing figure. He has been criticized for making unscientific and misleading statements, including COVID-19 misinformation, affirming antisemitic and transphobic comments, and promoting conspiracy theories. His ownership of Twitter has been controversial because of large employee layoffs, an increase in posts containing hate speech, misinformation and disinformation on the service, and changes to service features, including verification. 
By early 2024, Musk became active in American politics as a vocal and financial supporter of US presidential candidate Donald Trump, becoming the largest political donor of the 2024 election. After winning in November, Trump announced that he had chosen Musk along with Vivek Ramaswamy to co-lead his planned Department of Government Efficiency (DOGE) advisory board, which is tasked with removing regulations in order to reduce expenditures and increase government efficiency.

Page: Views of Elon Musk
Summary: Elon Musk is the CEO or owner of multiple companies including Tesla, SpaceX, and X Corp., and has expressed many views on a wide variety of subjects, ranging from politics to science.
Musk has often been described as libertarian, but also describes himself as "politically moderate". Following the COVID-19 pandemic, however, his views have also been described as becoming more right-wing and conservative over time, sometimes being described as far-right. Within the context of American politics, Musk supported Barack Obama in 2008 and 2012, Hillary Clinton in 2016, Joe Biden in 2020, and Donald Trump in 2024. In 2022, Musk said he would start voting for Republican Party candidates, with him showing support for Vivek Ramaswamy in the 2024 Republican presidential primaries. He has stated support for universal basic income, gun rights, freedom of speech, a tax on carbon emissions and opposes government subsidies. He is also a critic of illegal immigration and short-selling.
Musk has expressed concern about issues such as artificial intelligence (AI), climate change and population decline. He has also criticized COVID-19 lockdowns, public transportation, and labor unions. He has promoted conspiracy theories, and made controversial statements that have led to accusations of sexism, antisemitism, support of white pride and transphobia. His views on international relations, including on the China-Taiwan and Russia-Ukraine conflicts, have received mixed reactions.

Page: Acquisition of Twitter by Elon Musk
Summary: The business magnate Elon Musk initiated an acquisition of American social media company Twitter, Inc. on April 14, 2022, and concluded it on October 27, 2022. Musk had begun buying shares of the company in January 2022, becoming its largest shareholder by April with a 9.1 percent ownership stake. Twitter invited Musk to join its board of directors, an offer he initially accepted before declining. On April 14, Musk made an unsolicited offer to purchase the company, to which Twitter's board responded with a "poison pill" strategy to resist a hostile takeover before unanimously accepting Musk's buyout offer of $44 billion on April 25. Musk stated that he planned to introduce new features to the platform, make its algorithms open-source, combat spambot accounts, and promote free speech, framing the acquisition as the cornerstone of X, an "everything app".
In July, Musk announced his intention to terminate the agreement, asserting that Twitter had breached their agreement by refusing to crack down on spambot accounts. The company filed a lawsuit against Musk in the Delaware Court of Chancery shortly thereafter, with a trial scheduled for the week of October 17. Weeks before the trial was set to begin, Musk reversed course, announcing that he would move forward with the acquisition. The deal was closed on October 28, with Musk immediately becoming Twitter's new owner and CEO. Twitter was taken private and merged into a new parent company named X Corp. Musk promptly fired several top executives, including previous CEO Parag Agrawal. Musk has since proposed several reforms to Twitter and laid off half of the company's workforce. Hundreds of employees then resigned from the company after Musk issued an ultimatum demanding they commit to "extremely hardcore" work. Linda Yaccarino was appointed CEO of X Corp. In July 2023, the Twitter service was rebranded as X.
Reactions to the buyout were mixed, with praise for Musk's planned reforms and vision for the company, particularly his calls for greater free speech, but criticism over fears of a potential rise in misinformation and disinformation, harassment, and hate speech on the platform. Within the United States, conservatives have largely supported the acquisition, while many liberals and former Twitter employees have voiced concerns about Musk's intentions. Since becoming owner, Musk has faced backlash for his handling of the company and account suspensions, including the December 2022 suspensions of ten journalists.

Result:
Page: Elon Musk Elon Musk, born June 28, 1971, is a businessman known for founding and leading SpaceX, Tesla, Inc., and several other companies like the Boring Company, Neuralink, and OpenAI. Musk, originally from South Africa, moved to the U.S., where he co-founded companies like Zip2 and PayPal. His ventures in space and electric vehicles have made him the wealthiest individual, with a net worth of $421 billion as of January 2025. Musk's acquisition of Twitter in 2022 led to rebranding it as X Corp. His actions and views, including political support for Donald Trump in 2024, have made him a polarizing figure.

Page: Views of Elon Musk Elon Musk, CEO of companies like Tesla and SpaceX, has expressed diverse views on politics and science. Initially seen as libertarian, his views have shifted towards conservative over time. He has supported various political candidates across the spectrum, from Barack Obama to Donald Trump. Musk advocates for universal basic income, gun rights, and a tax on carbon emissions, while opposing government subsidies and illegal immigration. He has voiced concerns about AI, climate change, and population decline, and has been criticized for promoting conspiracy theories and making controversial statements on various social issues.

Page: Acquisition of Twitter by Elon Musk Elon Musk acquired Twitter for $44 billion in 2022, merging it into X Corp. and rebranding the service as X. Initially, Musk was Twitter's largest shareholder and proposed several reforms for the platform, emphasizing free speech. After a legal dispute, the deal was finalized in October 2022. Musk's acquisition was met with mixed reactions, with supporters praising his free speech stance and critics worrying about increased misinformation and hate speech. His management style, including mass layoffs and policy changes, has drawn significant backlash.
'''.strip()